# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Role', verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[(b'user', 'User'), (b'admin', 'Admin')], max_length=5, null=True, verbose_name='Tipo'),
        ),
    ]
