# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-04 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171102_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
