# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_auto_20171214_2031'),
        ('accounts', '0006_auto_20171214_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modify')),
                ('folder', models.ManyToManyField(related_name='role', to='common.Carpeta', verbose_name='Folder')),
            ],
            options={
                'db_table': 'role',
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'default_related_name': 'role',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[(b'user', 'User'), (b'admin', 'Admin'), (b'manager', 'Manager')], max_length=5, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Role'),
        ),
    ]
