# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20171219_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(b'user', 'User'), (b'admin', 'Admin'), (b'manager', 'Manager')], default='user', max_length=5, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
