# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20171219_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(b'user', 'User'), (b'admin', 'Admin'), (b'manager', 'Manager')], max_length=7, verbose_name='Type'),
        ),
    ]
