# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 23:54
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FF0000', max_length=18, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Etiquetas'),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='icono',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Icono'),
        ),
    ]
