# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-08 02:03
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='Color'),
        ),
    ]
