# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-17 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20171010_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='icono',
            field=models.CharField(blank=True, default='folder', max_length=25, null=True, verbose_name='Icono'),
        ),
    ]
