# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-08 02:31
from __future__ import unicode_literals

from django.db import migrations
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20171008_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='icono',
            field=fontawesome.fields.IconField(blank=True, max_length=60, verbose_name='Icono'),
        ),
    ]
