# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-17 17:40
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20171017_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#DCDCDC', max_length=18, null=True, verbose_name='Color'),
        ),
    ]
