# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-08 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20171008_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpeta',
            name='icono',
            field=models.CharField(max_length=25, verbose_name='Icono'),
        ),
    ]
