# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20171017_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modify')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=75, verbose_name='Nombre')),
                ('carpetas', models.ManyToManyField(related_name='role', to='common.Carpeta')),
            ],
            options={
                'db_table': 'role',
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'default_related_name': 'role',
            },
        ),
    ]
