# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_role'),
        ('common', '0006_auto_20171110_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='carpetas',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
