# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 23:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0007_auto_20171115_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='created',
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='modified',
        ),
        migrations.AddField(
            model_name='archivo',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivo',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivo',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modified_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivo',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
