# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_configuracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='url_academico',
            field=models.URLField(blank=True, null=True, verbose_name='Academico'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='url_biblioteca',
            field=models.URLField(blank=True, null=True, verbose_name='Biblioteca'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='url_convocatoria',
            field=models.URLField(blank=True, null=True, verbose_name='Convocatorias'),
        ),
    ]
