# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20171124_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='archivo',
            field=models.FileField(upload_to='configuracion/%Y/%m/%d/', verbose_name='Archivo'),
        ),
    ]
