# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 22:28
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20171129_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modify')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('url_enlace', models.URLField(blank=True, null=True, verbose_name='URL enlace')),
                ('color', colorfield.fields.ColorField(blank=True, default='#BAA130', max_length=18, null=True, verbose_name='Color')),
                ('icono', models.CharField(blank=True, default='link', max_length=25, null=True, verbose_name='Icono')),
            ],
            options={
                'db_table': 'enlace',
                'verbose_name': 'Enlace',
                'verbose_name_plural': 'Enlaces',
                'default_related_name': 'enlace',
            },
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='url_academico',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='url_biblioteca',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='url_convocatoria',
        ),
    ]
