# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_auto_20171204_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='logo_blanco',
            field=models.ImageField(default='logo.png', upload_to='configuracion/%Y/%m/%d/', verbose_name='Logo Blanco'),
            preserve_default=False,
        ),
    ]
