# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 18:17
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_configuracion_logo_blanco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modify')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('url_link', models.URLField(blank=True, null=True, verbose_name='URL link')),
                ('color', colorfield.fields.ColorField(blank=True, default='#BAA130', max_length=18, null=True, verbose_name='Color')),
                ('icon', models.CharField(blank=True, default='link', max_length=25, null=True, verbose_name='Icon')),
            ],
            options={
                'db_table': 'link',
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'default_related_name': 'link',
            },
        ),
        migrations.DeleteModel(
            name='Enlaces',
        ),
    ]
