# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20171214_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivo',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='carpeta',
            options={'verbose_name': 'Folder', 'verbose_name_plural': 'Folders'},
        ),
        migrations.AlterModelOptions(
            name='configuracion',
            options={'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to='archivo/%Y/%m/%d/', verbose_name='_(Filer)'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='carpetas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivo', to='common.Carpeta', verbose_name='_(Folder)'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='icono',
            field=models.CharField(blank=True, default='folder', max_length=25, null=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carpeta', to='common.Carpeta', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='carpeta',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='archivo',
            field=models.ImageField(upload_to='configuracion/%Y/%m/%d/', verbose_name='_(Logo)'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='archivo_ayuda',
            field=models.FileField(blank=True, null=True, upload_to='configuracion/%Y/%m/%d/', verbose_name='_(File to help)'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='logo_blanco',
            field=models.ImageField(upload_to='configuracion/%Y/%m/%d/', verbose_name='_(White logo)'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
