# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20171214_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to='archivo/%Y/%m/%d/', verbose_name='Filer'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='carpetas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivo', to='common.Carpeta', verbose_name='Folder'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='archivo',
            field=models.ImageField(upload_to='configuracion/%Y/%m/%d/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='archivo_ayuda',
            field=models.FileField(blank=True, null=True, upload_to='configuracion/%Y/%m/%d/', verbose_name='File to help'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='logo_blanco',
            field=models.ImageField(upload_to='configuracion/%Y/%m/%d/', verbose_name='White logo'),
        ),
    ]
