# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20171214_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(upload_to='archivo/%Y/%m/%d/', verbose_name='File'),
        ),
    ]
