# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20171214_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuracion',
            old_name='archivo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='configuracion',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='configuracion',
            old_name='logo_blanco',
            new_name='white_logo',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='archivo_ayuda',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='help_file',
            field=models.FileField(blank=True, null=True, upload_to='configuracion/%Y/%m/%d/', verbose_name='Help file'),
        ),
    ]
