build:
  backend:
    image: python:2.7
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.test
      - SECRET_KEY=secret
      - DB_HOST=127.0.0.1
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - STATIC_URL=/static/
      - MEDIA_URL=/media/
      - BROKER_URL='redis://localhost:6379/0'
      - BROKER_RESULT_BACKEND='redis://localhost:6379/0'
    commands:
      - pip install -r requirements/test.txt --cache-dir pip_cache_dir
      - flake8 .
      - python manage.py test
compose:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
cache:
  mount:
    - .git
    - pip_cache_dir

deploy:
  ssh:
    host: host_deploy
    user: ubuntu
    commands:
      - cd /home/ubuntu/blindjupp/
      - source ../venv/bin/activate
      - git pull --rebase origin develop
      - pip install -t requirements/prod.txt
      - python manage.py migrate
      - python manage.py compilemessages
      - bower install
      - sudo supervisorctl restart all
    when:
      branch: develop
